stages:
  data_ingestion:
    cmd: python src/pipeline/stage_01_data_ingest_pipe.py
    deps:
      - src/pipeline/stage_01_data_ingest_pipe.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/test.csv
      - artifacts/data_ingestion/train.csv

  data_transformation:
    cmd: python src/pipeline/stage_02_data_transform_pipe.py
    deps:
      - src/pipeline/stage_02_data_transform_pipe.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation/final_test.csv
      - artifacts/data_transformation/final_train.csv
      - artifacts/data_transformation/preprocessor.pkl

  model_trainer:
    cmd: python src/pipeline/stage_03_model_train_pipe.py
    deps:
      - config/config.yaml
      - artifacts/data_transformation/final_test.csv
      - artifacts/data_transformation/final_train.csv
      - src/pipeline/stage_03_model_train_pipe.py
    outs:
      - artifacts/model_trainer/model.pkl

  model_evaluation:
    cmd: python src/pipeline/stage_04_model_eval.py
    deps:
      - src/pipeline/stage_04_model_eval.py
      - config/config.yaml
      - artifacts/data_transformation/final_test.csv
      - artifacts/model_trainer/model.pkl
    metrics:
      - artifacts/model_evaluation/metrics.json:
          cache: false